CC = gcc
CFLAGS = -Wall -gcc
OBJ = allocator.o tester.o

all: tester

tester: $(OBJ)
	$(CC) $(CFLAGS) -o tester $(OBJ) $(LIB)

allocator.o: allocator.c allocator.h
	$(CC) $(CFLAGS) -c allocator.c

tester.o: tester.c allocator.h
	$(CC) $(CFLAGS) -c tester.c

clean:
	rm -f